# Módulos e pacotes

## Módulos

Módulos no Python são arquivos de código python que contém código que
pode ser reutilizado em outros arquivos.
Funcionam parecido com o comando `source` do R

Algumas características importantes:

- São apenas arquivos de texto com extensão .py
- Podem conter definições de funções ou expressões para serem executadas.
- Possuem seu próprio `namespace`.
- Por padrão as funções não são 'anexadas' diretamente no namespace global.

In [2]:
import modulo

In [3]:
modulo.somar_um(3)

4

## Pacotes

Pacotes são conjuntos de módulos, em geral, organizados dentro de uma
pasta que contém um arquivo chamado `__init__.py` que define os módulos
que existem naquele pacote.

Na prática, funcionam de forma muito parecida com o que chamamos de módulo.
Pacotes no Python são muito parecidos com pacotes do R. Podem ser instalados,
compartilhados, etc. 

In [1]:
import numpy as np

In [4]:
np.sum([1,2,3])

6

In [5]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [6]:
help(np.sum)

Help on function sum in module numpy:

sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In 

In [5]:
from numpy import sum

In [6]:
help(sum)

Help on function sum in module numpy:

sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In 

In [8]:
sum([1,2,3])

6

In [10]:
from numpy import sum as np_sum

In [11]:
np_sum([1,2,3])

6

In [7]:
# from numpy import * # parece com o library(), cuidado! nao é boa pratica.

# Introdução ao Numpy

In [2]:
import numpy as np

In [3]:
# assim como no R, vetores do numpy possuem elementos homogêneos,
# isto é, todos os elementos são do mesmo tipo.
# isso também é a principal diferença entre um array e uma lista.
x = np.array([1,2,3])
x

array([1, 2, 3])

In [4]:
x.shape

(3,)

In [5]:
x.dtype

dtype('int64')

In [6]:
# assim como no R, operações com arrays do mesmo tamanho acontecem 
# elemento a elemento.
x + x 

array([2, 4, 6])

In [7]:
# arrays possuem métodos
x.mean()

2.0

In [8]:
# também é possível usar funções direto do numpy.
np.mean(x)

2.0

In [ ]:
help(x.mean)
help(np.mean)

## Subsetting

In [9]:
x = np.array(range(10))
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
x[0]

0

In [11]:
x[-1]

9

In [13]:
print(x > 5)
x[x>5]

[False False False False False False  True  True  True  True]


array([6, 7, 8, 9])

In [15]:
x[0:3]

array([0, 1, 2])

In [16]:
x[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x[:3]

array([0, 1, 2])

In [18]:
x[-5:]

array([5, 6, 7, 8, 9])

## Broadcasting

In [19]:
x = np.array([1,2,3,4])
x + 1

array([2, 3, 4, 5])

In [20]:
y = np.array([1,2])
x + y

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [21]:
y = np.array([1])
x + y

array([2, 3, 4, 5])

## Números aleatórios

In [24]:
import random


In [25]:
x = np.random.normal(0, 1, (10,))
x

array([-1.92575327,  0.44242859, -1.35265359,  0.59617823,  0.37591623,
       -1.62512797, -0.73479577, -1.10860794,  0.79976262, -1.47305373])

In [26]:
x.shape

(10,)

## Lógicos/booleanos

In [31]:
x = np.random.normal(0, 1, (10,))
print(x)

[-0.97499022  0.18922814 -0.34094696  0.49434866 -0.31159744  0.18799487
  0.3762586  -1.60377841  0.04962024  0.19222449]


In [33]:
y = x > 0
print(y)

[False  True False  True False  True  True False  True  True]


In [34]:
y.dtype

dtype('bool')

In [35]:
y.any( ) # ??

True

In [36]:
y.all() # ??

False

In [56]:
y.sum()

6

Bad pipe message: %s [b"\xb3\x80\xa2\xaf\x88\x86\xb2\x1a\xd9\x85\xd1\x96\x0b\xd1\xe7w\xa2$\x00\x00|\xc0,\xc00\x00\xa3\x00\x9f\xcc\xa9\xcc\xa8\xcc\xaa\xc0\xaf\xc0\xad\xc0\xa3\xc0\x9f\xc0]\xc0a\xc0W\xc0S\xc0+\xc0/\x00\xa2\x00\x9e\xc0\xae\xc0\xac\xc0\xa2\xc0\x9e\xc0\\\xc0`\xc0V\xc0R\xc0$\xc0(\x00k\x00j\xc0#\xc0'\x00g\x00@\xc0\n\xc0\x14\x009\x008\xc0\t\xc0\x13\x003\x002\x00\x9d\xc0\xa1\xc0\x9d\xc0Q\x00\x9c\xc0\xa0\xc0\x9c\xc0P\x00=\x00<\x005\x00/\x00\x9a\x00\x99\xc0\x07\xc0\x11\x00\x96\x00\x05\x00\xff\x01\x00\x00j\x00\x00\x00\x0e\x00\x0c\x00\x00\t127.0.0.1\x00\x0b\x00\x04\x03\x00\x01\x02\x00\n\x00\x0c\x00\n\x00\x1d\x00\x17\x00\x1e\x00", b'\x18\x00#\x00\x00\x00\x16\x00\x00\x00\x17\x00\x00\x00\r\x000\x00.\x04\x03\x05\x03\x06']
Bad pipe message: %s [b'\x07\x08']
Bad pipe message: %s [b'\t\x08\n\x08\x0b\x08\x04']
Bad pipe message: %s [b'\x08\x06\x04\x01\x05\x01\x06', b'', b'\x03\x03']
Bad pipe message: %s [b'']
Bad pipe message: %s [b'\xd4\x1b"\xe8\x8a\xf1\x9c\x9a\x07\x82\x06W\x03W\x1f~\x16\x8